### ISSUE TITLE
Cannot create multiple probe at once

### ISSUE THREAD

**Issue by MadJlzz** [MadJlzz/madprobectl#2]
Give then file: 
```yaml
http:
  - name: simple-service-http
    url: http://localhost:8080/actuator/health
    delay: 5
  - name: other-simple-http
    url: http://localhost:8080/actuator/health
    delay: 10
```
it creates only the first probe from the `yaml`

Desired state is to create all probes from the file.
